name: cerina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  auth0_flutter: ^1.12.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
    - .env

  uses-material-design: true
